name = "pricna-api"
main = "worker.js"
compatibility_date = "2024-10-01"

[env.production]
# D1 Database
[[env.production.d1_databases]]
binding = "DB"
database_name = "pricna-db"
database_id = "349fbd92-9ef6-486f-bc7d-332ceb471c73"

# Environment Variables
[env.production.vars]
NODE_ENV = "production"
PORT = "8787"
FRONTEND_URL = "https://pricna.cz"
ADMIN_URL = "https://rezervace.pricna.cz"

# Secrets (nastavíte přes wrangler secret)
# MAILTRAP_HOST
# MAILTRAP_PORT
# MAILTRAP_USER
# MAILTRAP_PASS
# EMAIL_RESERVATIONS
# EMAIL_INFO
# EMAIL_OWNER
# JWT_SECRET
# ADMIN_USERNAME
# ADMIN_PASSWORD_HASH
